package ru.mycompany.tests;

import javax.xml.bind.DatatypeConverter;
import java.io.ByteArrayOutputStream;
import java.util.zip.GZIPOutputStream;

public class Custom {
    public static void main(String[] args) throws Exception {
        String str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<data>\n" +
                "  <formname>ТХУ-3</formname>\n" +
                "  <tv>4.0.1</tv>\n" +
                "  <FIO_podp>Тыблочкина Анна Ивановна</FIO_podp>\n" +
                "  <docmm>\n" +
                "    <Bw_Dt_time>04:30</Bw_Dt_time>\n" +
                "    <Bw_Dt_date>16.12.2016</Bw_Dt_date>\n" +
                "    <Endw_Dt_time>16:25</Endw_Dt_time>\n" +
                "    <Endw_Dt_date>16.12.2016</Endw_Dt_date>\n" +
                "    <Mm_Num>540</Mm_Num>\n" +
                "    <appeal/>\n" +
                "    <Mm_Type>0</Mm_Type>\n" +
                "    <Frest_B_Dt>16.12.2016 12:00</Frest_B_Dt>\n" +
                "    <Frest_E_Dt/>\n" +
                "    <Frest_Obor/>\n" +
                "    <Loc_Frest_1>40</Loc_Frest_1>\n" +
                "    <Loc_Frest_2>0</Loc_Frest_2>\n" +
                "    <Tip_Mm>701</Tip_Mm>\n" +
                "    <Priz_Sriv>0</Priz_Sriv>\n" +
                "    <Priz_Korr>0</Priz_Korr>\n" +
                "    <ID_MM>52</ID_MM>\n" +
                "  </docmm>\n" +
                "  <docmme>\n" +
                "    <rowE>\n" +
                "      <Name>AЛEKCAHДPOB AЛEKCAHДP AЛEKCAHДPOBИЧ</Name>\n" +
                "      <Tab_Num>20201</Tab_Num>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Id_Dp>Машинист работает за машиниста</Id_Dp>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <Pn>1</Pn>\n" +
                "    </rowE>\n" +
                "  </docmme>\n" +
                "  <toplivo>\n" +
                "    <row>\n" +
                "      <Sec_Mod>482</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ЭВС-2</Sec_Mod_Name>\n" +
                "      <Sec_Num>00008080</Sec_Num>\n" +
                "      <Sec_Code>01</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>05:29</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>06:05</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time>06:06</Cpout_dt_time>\n" +
                "      <Cpout_dt_date>16.12.2016</Cpout_dt_date>\n" +
                "      <Cpin_dt_time>06:21</Cpin_dt_time>\n" +
                "      <Cpin_dt_date>16.12.2016</Cpin_dt_date>\n" +
                "      <E_dt_time>06:23</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>1</P_Oper>\n" +
                "      <P_Oper_Name>Технологические маневровые передвижения ТПС</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>1</Pr_El>\n" +
                "      <Pr_El_Name>переменный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>483</Sec_Mod>\n" +
                "      <Sec_Mod_Name>Sm6</Sec_Mod_Name>\n" +
                "      <Sec_Num>00002710</Sec_Num>\n" +
                "      <Sec_Code>01</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>06:23</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>07:00</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time/>\n" +
                "      <Cpout_dt_date/>\n" +
                "      <Cpin_dt_time/>\n" +
                "      <Cpin_dt_date/>\n" +
                "      <E_dt_time>08:28</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>2</P_Oper>\n" +
                "      <P_Oper_Name>Простой ТПС в работоспособном состоянии (прогрев)</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>2</Pr_El>\n" +
                "      <Pr_El_Name>постоянный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>273</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ЭП20</Sec_Mod_Name>\n" +
                "      <Sec_Num>00001111</Sec_Num>\n" +
                "      <Sec_Code>01</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>09:20</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>09:20</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time>09:21</Cpout_dt_time>\n" +
                "      <Cpout_dt_date>16.12.2016</Cpout_dt_date>\n" +
                "      <Cpin_dt_time>09:40</Cpin_dt_time>\n" +
                "      <Cpin_dt_date>16.12.2016</Cpin_dt_date>\n" +
                "      <E_dt_time>09:42</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>1</P_Oper>\n" +
                "      <P_Oper_Name>Технологические маневровые передвижения ТПС</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>1</Pr_El>\n" +
                "      <Pr_El_Name>переменный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>486</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ЭС1</Sec_Mod_Name>\n" +
                "      <Sec_Num>00005911</Sec_Num>\n" +
                "      <Sec_Code>01</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>09:42</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>09:48</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time/>\n" +
                "      <Cpout_dt_date/>\n" +
                "      <Cpin_dt_time/>\n" +
                "      <Cpin_dt_date/>\n" +
                "      <E_dt_time>10:00</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>2</P_Oper>\n" +
                "      <P_Oper_Name>Простой ТПС в работоспособном состоянии (прогрев)</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>2</Pr_El>\n" +
                "      <Pr_El_Name>постоянный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>271</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ВЛ82</Sec_Mod_Name>\n" +
                "      <Sec_Num>00004911</Sec_Num>\n" +
                "      <Sec_Code>01</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>10:22</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>10:24</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time>10:25</Cpout_dt_time>\n" +
                "      <Cpout_dt_date>16.12.2016</Cpout_dt_date>\n" +
                "      <Cpin_dt_time>10:33</Cpin_dt_time>\n" +
                "      <Cpin_dt_date>16.12.2016</Cpin_dt_date>\n" +
                "      <E_dt_time>10:37</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>1</P_Oper>\n" +
                "      <P_Oper_Name>Технологические маневровые передвижения ТПС</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>2</Pr_El>\n" +
                "      <Pr_El_Name>постоянный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>272</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ВЛ82М</Sec_Mod_Name>\n" +
                "      <Sec_Num>00004911</Sec_Num>\n" +
                "      <Sec_Code>02</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>10:38</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>10:40</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time/>\n" +
                "      <Cpout_dt_date/>\n" +
                "      <Cpin_dt_time/>\n" +
                "      <Cpin_dt_date/>\n" +
                "      <E_dt_time>11:01</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>2</P_Oper>\n" +
                "      <P_Oper_Name>Простой ТПС в работоспособном состоянии (прогрев)</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>1</Pr_El>\n" +
                "      <Pr_El_Name>переменный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>275</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ЭП10</Sec_Mod_Name>\n" +
                "      <Sec_Num>00000345</Sec_Num>\n" +
                "      <Sec_Code>01</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>11:02</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>11:05</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time/>\n" +
                "      <Cpout_dt_date/>\n" +
                "      <Cpin_dt_time/>\n" +
                "      <Cpin_dt_date/>\n" +
                "      <E_dt_time>11:23</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>2</P_Oper>\n" +
                "      <P_Oper_Name>Простой ТПС в работоспособном состоянии (прогрев)</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>1</Pr_El>\n" +
                "      <Pr_El_Name>переменный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>481</Sec_Mod>\n" +
                "      <Sec_Mod_Name>ЭД4ДК</Sec_Mod_Name>\n" +
                "      <Sec_Num>00000345</Sec_Num>\n" +
                "      <Sec_Code>02</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>11:29</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>11:30</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time>11:31</Cpout_dt_time>\n" +
                "      <Cpout_dt_date>16.12.2016</Cpout_dt_date>\n" +
                "      <Cpin_dt_time>11:42</Cpin_dt_time>\n" +
                "      <Cpin_dt_date>16.12.2016</Cpin_dt_date>\n" +
                "      <E_dt_time>11:44</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>1</P_Oper>\n" +
                "      <P_Oper_Name>Технологические маневровые передвижения ТПС</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>2</Pr_El>\n" +
                "      <Pr_El_Name>постоянный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "    <row>\n" +
                "      <Sec_Mod>276</Sec_Mod>\n" +
                "      <Sec_Mod_Name>2ЭВ120</Sec_Mod_Name>\n" +
                "      <Sec_Num>00000345</Sec_Num>\n" +
                "      <Sec_Code>02</Sec_Code>\n" +
                "      <Id_Org_P>2806</Id_Org_P>\n" +
                "      <Id_Org_P_Name>ТЧЭ-6 СЕВ</Id_Org_P_Name>\n" +
                "      <Id_Org_P_DorId>28</Id_Org_P_DorId>\n" +
                "      <Id_Org_P_DorName>Северная</Id_Org_P_DorName>\n" +
                "      <Prev_E_dt_time>11:44</Prev_E_dt_time>\n" +
                "      <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "      <B_dt_time>11:50</B_dt_time>\n" +
                "      <B_dt_date>16.12.2016</B_dt_date>\n" +
                "      <Cpout_dt_time/>\n" +
                "      <Cpout_dt_date/>\n" +
                "      <Cpin_dt_time/>\n" +
                "      <Cpin_dt_date/>\n" +
                "      <E_dt_time>12:21</E_dt_time>\n" +
                "      <E_dt_date>16.12.2016</E_dt_date>\n" +
                "      <Id_St>2806</Id_St>\n" +
                "      <Name_st>ТЧЭ-6 СЕВ</Name_st>\n" +
                "      <Id_St_DorId>28</Id_St_DorId>\n" +
                "      <Id_St_DorName>Северная</Id_St_DorName>\n" +
                "      <P_Oper>2</P_Oper>\n" +
                "      <P_Oper_Name>Простой ТПС в работоспособном состоянии (прогрев)</P_Oper_Name>\n" +
                "      <Tech_Eq_0/>\n" +
                "      <B_Counter_0>160934</B_Counter_0>\n" +
                "      <B_Counter_1>160934</B_Counter_1>\n" +
                "      <B_Counter_2>160935</B_Counter_2>\n" +
                "      <Q_1/>\n" +
                "      <Id_Fe/>\n" +
                "      <Id_Fe_Name/>\n" +
                "      <Tech_Eq/>\n" +
                "      <Id_Fmu/>\n" +
                "      <Id_Fmu_Name/>\n" +
                "      <Doc_Num/>\n" +
                "      <Doc_Date/>\n" +
                "      <Pr_El>1</Pr_El>\n" +
                "      <Pr_El_Name>переменный</Pr_El_Name>\n" +
                "      <Pr_Ter_0/>\n" +
                "      <flag_electr/>\n" +
                "      <ID_MM>1921</ID_MM>\n" +
                "      <H_Counter_0>0</H_Counter_0>\n" +
                "      <H_Counter_1>0</H_Counter_1>\n" +
                "      <H_Counter_2>0</H_Counter_2>\n" +
                "      <Tech_Eq_2>0.000</Tech_Eq_2>\n" +
                "      <Q_0>0</Q_0>\n" +
                "      <Id_Store_Org>0</Id_Store_Org>\n" +
                "      <Pr_Fe_Seq_Off>0</Pr_Fe_Seq_Off>\n" +
                "    </row>\n" +
                "  </toplivo>\n" +
                "  <docslog>\n" +
                "    <DOC_CR_DT>16.12.2016 12:00</DOC_CR_DT>\n" +
                "    <ID_DOR_ORG>423</ID_DOR_ORG>\n" +
                "    <ID_ORG>423</ID_ORG>\n" +
                "    <USER_ID>523</USER_ID>\n" +
                "  </docslog>\n" +
                "  <locomotives>\n" +
                "    <rowL>\n" +
                "      <Sec_Mod>23</Sec_Mod>\n" +
                "      <Sec_Num>423</Sec_Num>\n" +
                "      <Sec_Code>423</Sec_Code>\n" +
                "      <Id_Org_P>523</Id_Org_P>\n" +
                "      <rowO>\n" +
                "        <P_Oper_Add>2</P_Oper_Add>\n" +
                "        <B_dt_date>16.12.2016</B_dt_date>\n" +
                "        <B_dt_time>12:00</B_dt_time>\n" +
                "        <E_dt_date>16.12.2016</E_dt_date>\n" +
                "        <E_dt_time>12:00</E_dt_time>\n" +
                "        <Id_St>42</Id_St>\n" +
                "        <P_Oper>3</P_Oper>\n" +
                "        <Prev_E_dt_date>16.12.2016</Prev_E_dt_date>\n" +
                "        <Prev_E_dt_time>12:00</Prev_E_dt_time>\n" +
                "        <Tech_Eq_0>32</Tech_Eq_0>\n" +
                "        <B_Counter_0>12</B_Counter_0>\n" +
                "        <H_Counter_0>54</H_Counter_0>\n" +
                "        <B_Counter_1>34</B_Counter_1>\n" +
                "        <H_Counter_1>23</H_Counter_1>\n" +
                "        <Tech_Eq_2>65</Tech_Eq_2>\n" +
                "        <B_Counter_2>43</B_Counter_2>\n" +
                "        <H_Counter_2>12</H_Counter_2>\n" +
                "        <Id_Fe>54</Id_Fe>\n" +
                "        <Tech_Eq>23</Tech_Eq>\n" +
                "        <Doc_Num>23</Doc_Num>\n" +
                "        <Doc_Date>16.12.2016</Doc_Date>\n" +
                "        <Q_0>23</Q_0>\n" +
                "        <Q_1>452</Q_1>\n" +
                "        <Id_Store_Org>532</Id_Store_Org>\n" +
                "        <Cpout_dt_date>16.12.2016</Cpout_dt_date>\n" +
                "        <Cpout_dt_time>12:00</Cpout_dt_time>\n" +
                "        <Cpin_dt_date>16.12.2016</Cpin_dt_date>\n" +
                "        <Cpin_dt_time>12:00</Cpin_dt_time>\n" +
                "        <Pr_Fe_Seq_Off>634</Pr_Fe_Seq_Off>\n" +
                "        <Pr_El>123</Pr_El>\n" +
                "        <Id_Fmu>532</Id_Fmu>\n" +
                "        <Pr_Ter_0>324</Pr_Ter_0>\n" +
                "      </rowO>\n" +
                "    </rowL>\n" +
                "  </locomotives>\n" +
                "</data>\n";
        ByteArrayOutputStream obj=new ByteArrayOutputStream();
        GZIPOutputStream gzip = new GZIPOutputStream(obj);
        gzip.write(str.getBytes("UTF-8"));
        gzip.close();
        System.out.println(DatatypeConverter.printHexBinary(obj.toByteArray()));
    }
}
